Add methods parsing query parameters and storing tokens to a localsto…
OneCareerJP/cognito-util pull request #1
Opened 2020-10-14 09:59 UTC by shskwmt

Add following methods to CognitUtil

** 1. storeTokenFromQueryString **

This method parses a callback url's query string and retrieves access_token, id_token and expires_in. Then it stores these values to a localstorage through `storeToken` method.

** 2. storeToken **

This method stores access_token, id_token and expires_in to a localstorage.

2020-10-14 10:23 UTC, qpSHiNqp requested changes
Copyright のあとは著作権者書かないといけないと思います。
`const` な変数には方宣言入れないって感じですよね？

2020-10-14 10:23 UTC, qpSHiNqp commented on MIT-LICENSE
> +Copyright 2020
```suggestion
Copyright 2020 ONE CAREER, Inc.
```

2020-10-15 00:30 UTC, shskwmt commented
Thank you for your comments.

> Copyright のあとは著作権者書かないといけないと思います。

Oh, I forgot it. I'll do so!

> `const` な変数には方宣言入れないって感じですよね？

I think it is better to omit a type annotation when it can be inferred.

2020-10-15 05:53 UTC, qpSHiNqp approved these changes
Thank you, fixes are confirmed.

2020-10-15 05:53 UTC, merged